services:
  - type: web
    name: breco-backend
    env: php
    plan: starter
    buildCommand: |
      cp .env.example .env
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
    startCommand: |
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - fromGroup: breco-db
